### ISSUE TITLE
LSPDR crashing due to Supercallouts?

### ISSUE THREAD

**Issue by Singhkiller1666** [SuperPyroManiac/SuperPlugins#11]
I recently installed Supercallouts and before I did lspdfr was working fine but now it just ends up getting stuck at the loading screen and doesn’t load into the game. Then it says lspdfr has crashed. Is this due to supercallouts? How can I fix this?

**Comment by SuperPyroManiac** [comment]
Can you post your RagePlugonHook.log

**Comment by SuperPyroManiac** [comment]
This issue does not seem related to SuperCallouts. This plugin does not load during the start screen. No log has been posted so I am closing it.
