### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Airdrigh75** [SuperPyroManiac/SuperPlugins#6]
Hello!
First of all I would like to share with how much I appreciate your work and contribution to the LSPDFR. These scripts are my favourite. Good job! Pls continue!

I share with you my two logs what I supposed record crashes maybe caused by latest superevents.

[RagePluginHook.log](https://github.com/SuperPyroManiac/SuperPlugins/files/3725570/RagePluginHook.log)
[RagePluginHook2.log](https://github.com/SuperPyroManiac/SuperPlugins/files/3725571/RagePluginHook2.log)

Moreover I would share with you my ideas.
1. Drunk/mentally confused army personnel. When arrest them you have to call military/usaf police. Subject could go crazy and start shooting, or attack you or be calm...
2. Illegal immigrants working. I see there are cleaners washing windows and workers on constructions. They should be checked and if they don’t have proper documents border patrol can be called to arrest and transport them.
3. This is a script idea because I don’t have enough knowledge to start and as I respect your work I will share with you. I found out there is no proper traffic control script yet. I mean something which could take the vehicles control from the ai. It is very annoying sometimes the ai vehicles don’t want to go and stop blocking the traffic. If there would be the possibility to get the control over them and show/appoint them the direction where to which means you get them through the situation. You could use the flashlight to appoint the ai vehicle and as in the traffic policier script a red marking could show where you want them to go. If you interested let me know and I can give you more details.

Best wishes,
Krisztian

**Comment by SuperPyroManiac** [comment]
Issue found. Looks like the ped was invalid when the script tried to kill them. Adding a fix now.
