### ISSUE TITLE
Interaction as "Y" key

### ISSUE THREAD

**Issue by Andy55596** [SuperPyroManiac/SuperPlugins#7]
By default Y key is set for interaction, I changed it to L in ini file but it did not change. The line in ini is
Interact = Keys.L
Am I doing something wrong, because Y still opens the Interaction menu.

**Comment by SuperPyroManiac** [comment]
I made a mistake with the config, try setting the option as "L" instead of "Keys.L"

**Comment by Andy55596** [comment]
Thanks

**Comment by SuperPyroManiac** [comment]
Issue fixed, thanks for letting me know!
